import { strict as assert } from "node:assert";
import { readFileSync } from "node:fs";
import { describe, it } from "node:test";

import { renderHtml } from "../../src/report/html.ts";
import { buildHtmlReportModel, safeEvidenceHref } from "../../src/report/html-model.ts";
import { buildReport } from "../../src/core/build-report.ts";
import { runDocument } from "../../src/core/engine.ts";
import { defineRule } from "../../src/core/rule.ts";
import { loadCorpus } from "../fixtures/corpus.ts";
import {
  canonicalReportStates,
  cleanReportState,
  findingsReportState,
  infrastructureReportState,
  insufficientCoverageReportState,
} from "../fixtures/report-states.ts";
import {
  BROWSER_VERSION_PATTERN,
  DECLARED_ENVIRONMENT_FIELDS,
  REQUIRED_BROWSER_RENDER_ARGS,
  REVIEW_ARTIFACT_CONTRACT_VERSION,
  assessHumanGate,
  isMeasurableBrowserVersion,
  validateReviewLedger,
  type ReviewLedger,
  type ReviewRound,
} from "../tools/report-surface-contract.mjs";

describe("HTML Report Surface v2", () => {
  it("renders the current package version on every canonical review surface", () => {
    const currentVersion = (JSON.parse(
      readFileSync(new URL("../../package.json", import.meta.url), "utf8"),
    ) as { version: string }).version;
    for (const [state, report] of Object.entries(canonicalReportStates())) {
      assert.equal(report.tool.version, currentVersion, `${state}: fixture advertises a stale product version`);
      const html = renderHtml(report);
      assert.match(html, new RegExp(`v${currentVersion.replaceAll(".", "\\.")} · report schema`, "u"));
      assert.match(html, new RegExp(`Generated by breaklint ${currentVersion.replaceAll(".", "\\.")}`, "u"));
    }
  });

  it("renders four status-true verdict families with their gate effect before details", () => {
    const expected = {
      clean: ["Clean run", "Coverage met", "Build passes (exit 0)."],
      findings: ["Findings block this run", "The finding gate was triggered", "Build fails (exit 1)."],
      infrastructure: ["Checker failed", "This is not a clean run", "Build fails (exit 3)."],
      "insufficient-coverage": ["Not enough was measured", "This is not a clean run", "Build fails (exit 4)."],
    } as const;
    for (const [state, report] of Object.entries(canonicalReportStates())) {
      const html = renderHtml(report);
      for (const text of expected[state as keyof typeof expected]) assert.ok(html.includes(text), `${state}: missing ${text}`);
      assert.ok(html.indexOf("Gate effect") < html.indexOf("Run summary"), `${state}: gate effect is buried below details`);
      assert.equal((html.match(/<main\b/gu) ?? []).length, 1, `${state}: requires exactly one main landmark`);
      assert.equal((html.match(/<h1\b/gu) ?? []).length, 1, `${state}: requires exactly one h1`);
    }
  });

  it("never lends clean-run wording to infrastructure or insufficient coverage", () => {
    for (const report of [infrastructureReportState(), insufficientCoverageReportState()]) {
      const html = renderHtml(report);
      assert.match(html, /Partial findings only/u);
      assert.doesNotMatch(html, /Nothing reached the gate/u);
      assert.doesNotMatch(html, /The requested checks completed without/u);
      assert.match(html, /Finding gate candidate<\/dt><dd>error/u);
      assert.match(html, /gate triggered by<\/dt><dd>none/u);
    }
  });

  it("never calls partial infrastructure measurement trusted coverage", () => {
    const report = infrastructureReportState();
    const model = buildHtmlReportModel(report);
    assert.equal(model.coverageTrust.label, "Not trustworthy");
    assert.equal(model.coverageTrust.measured, 20, "partial measured count must remain visible");
    assert.equal(model.coverageTrust.candidates, 22, "partial candidate count must remain visible");
    assert.match(model.coverageTrust.detail, /Partial measurement only: 20 of 22 candidates measured/u);

    const html = renderHtml(report);
    const summary = /<dl class="summary-grid">([\s\S]*?)<\/dl>/u.exec(html)?.[1] ?? "";
    assert.match(summary, /Not trustworthy/u);
    assert.match(summary, /20 of 22 candidates measured before the checker failed/u);
    assert.doesNotMatch(summary, /Coverage met/u, "the primary trust summary contradicts the exit-3 verdict");
  });

  it("keeps the real engine-to-HTML zero-candidate exit-4 path explicitly unestablished", () => {
    const snapshot = loadCorpus()[0]?.snapshot;
    assert.ok(snapshot);
    const zeroCandidateRule = defineRule({
      id: "test/zero-candidate",
      severity: "warn",
      proofSource: null,
      calibrated: false,
      experimental: false,
      unit: "candidates",
      defaultOptions: {},
      summary: "Produces no candidates for the exit-4 report contract control.",
      declines: [],
    }, () => ({ findings: [], candidates: 0, measured: 0, notMeasured: [], evaluations: [] }));
    const outcome = runDocument(
      { path: "zero-candidate.html", snapshot, infrastructure: [] },
      { failOn: "error", activeRules: [zeroCandidateRule], optionsByRule: {}, coverageFloors: {} },
    );
    const base = findingsReportState();
    const report = buildReport({
      outcomes: [outcome],
      mode: "demo",
      source: "handwritten snapshot fixture",
      toolVersion: "0.2.0",
      commit: null,
      startedAt: "1970-01-01T00:00:00.000Z",
      durationMs: 0,
      rulesRun: 1,
      environment: base.environment,
      config: base.config,
      failOn: "error",
    });

    assert.equal(outcome.report.coverage[zeroCandidateRule.id]?.ok, true, "zero candidates are not a per-rule floor failure");
    assert.equal(report.runVerdict, "insufficient-coverage");
    assert.equal(report.exitCode, 4);
    assert.equal(report.measuredRules, 0);
    const model = buildHtmlReportModel(report);
    assert.equal(model.coverageTrust.label, "Not established");
    assert.match(model.coverageTrust.detail, /no rule measured a candidate/iu);
    const summary = /<dl class="summary-grid">([\s\S]*?)<\/dl>/u.exec(renderHtml(report))?.[1] ?? "";
    assert.match(summary, /Not established/u);
    assert.doesNotMatch(summary, /Coverage met/u, "exit 4 must outrank a per-row zero-candidate ok flag");
  });

  it("renders positive apparatus evidence as clean and reserves failure wording for exit 3", () => {
    const states = canonicalReportStates();
    for (const [state, report] of Object.entries(states)) {
      const html = renderHtml(report);
      assert.equal(
        html.includes('id="apparatus-heading"'),
        state === "clean" || state === "infrastructure",
        `${state}: apparatus visibility drift`,
      );
      assert.equal(html.includes("Checker failure"), state === "infrastructure", `${state}: failure wording drift`);
      assert.equal(html.includes("Measurement apparatus"), state === "clean", `${state}: positive heading drift`);
      assert.equal(html.includes("geometry-cross-check-passed"), state === "clean", `${state}: positive event drift`);
      if (state === "clean") assert.doesNotMatch(html, /This is not a clean run/u);
      assert.equal(html.includes('id="coverage-alert-heading"'), state === "insufficient-coverage", `${state}: alert visibility drift`);
    }
  });

  it("renders every finding as a vertical semantic article with the complete evidence grammar", () => {
    const report = findingsReportState();
    const html = renderHtml(report);
    assert.equal((html.match(/<article class="finding /gu) ?? []).length, report.findings.length);
    for (const field of ["Document", "Source", "Measured", "Threshold", "Calibration", "Proof source", "Evidence:"]) {
      assert.ok(html.includes(field), `finding grammar is missing ${field}`);
    }
    assert.ok(html.includes(report.findings[0]!.message), "the full finding explanation is absent");
    assert.match(html, /Unknown — no source location was measured/u, "unknown source must stay explicit");
    assert.match(html, /Bound evidence/u);
    assert.match(html, /does not bind this finding/u);
    assert.match(html, /Ambiguity:/u);
    assert.doesNotMatch(html, /<table\b/u, "findings and coverage must reflow instead of requiring a table scroll");
  });

  it("uses unique deterministic IDs for every labelled surface", () => {
    const html = renderHtml(findingsReportState());
    const ids = [...html.matchAll(/\sid="([^"]+)"/gu)].map((match) => match[1]);
    assert.equal(new Set(ids).size, ids.length, "duplicate HTML IDs break label relationships");
    for (const target of [...html.matchAll(/aria-labelledby="([^"]+)"/gu)].map((match) => match[1]!)) {
      assert.ok(ids.includes(target), `aria-labelledby points at missing id ${target}`);
    }
  });

  it("only activates tool-owned relative evidence paths", () => {
    for (const unsafe of [
      "https://attacker.example/evidence.png",
      "javascript:alert(1)",
      "file:///etc/passwd",
      "/tmp/report-page-001.png",
      "../secret-page-001.png",
      "evidence/not-a-tool-file.png",
      "evidence\\report-page-001.png",
    ]) {
      assert.equal(safeEvidenceHref(unsafe), null, unsafe);
    }
    assert.equal(safeEvidenceHref("evidence/report-page-001.png"), "evidence/report-page-001.png");
    assert.equal(safeEvidenceHref("report name-page-001.png"), null, "spaces are not minted by the tool key");

    const report = findingsReportState();
    report.findings[0]!.evidence = { ref: 'javascript:alert("owned")', bindsFinding: true };
    const html = renderHtml(report);
    assert.ok(html.includes("javascript:alert(&quot;owned&quot;)"), "unsafe reference should remain visible as text");
    assert.doesNotMatch(html, /href="javascript:/u, "unsafe reference became navigable");
  });

  it("escapes hostile report text without breaking the semantic structure", () => {
    const report = findingsReportState();
    report.findings[0]!.message = '<script>window.evil = true</script> & "quoted"\u0007';
    report.findings[0]!.document = 'x" aria-label="forged.html';
    const html = renderHtml(report);
    assert.doesNotMatch(html, /<script/iu);
    assert.match(html, /&lt;script&gt;window\.evil = true&lt;\/script&gt; &amp; &quot;quoted&quot;�/u);
    assert.doesNotMatch(html, /[\u0000-\u0008\u000b\u000c\u000e-\u001f]/u);
  });

  it("is self-contained, responsive, print-safe and reduced-motion aware", () => {
    const html = renderHtml(cleanReportState());
    for (const forbidden of [/<script/iu, /@import/iu, /<link\b/iu, /src\s*=\s*["']https?:/iu]) {
      assert.doesNotMatch(html, forbidden);
    }
    assert.match(html, /Content-Security-Policy/u);
    assert.match(html, /@media \(max-width: 30rem\)/u);
    assert.match(html, /@media \(prefers-reduced-motion: reduce\)/u);
    assert.match(html, /@page \{ size: A4; margin: 12mm; \}/u);
    assert.match(html, /@media print/u);
    assert.match(html, /<section class="findings-section findings-empty"/u, "clean findings must remain explicit on screen and targetable in print");
    assert.match(html, /\.summary-grid \{ grid-template-columns: minmax\(0, 1\.7fr\) repeat\(3, minmax\(0, 1fr\)\); \}/u, "print must reserve enough width for the complete Coverage Trust verdict");
    assert.match(html, /\.summary-grid > div:first-child dd \{[^}]*white-space: nowrap/su, "Coverage Trust label must stay intact in print");
    assert.match(html, /\.coverage-list \{ display: block; \}/u, "print coverage must leave the fragment-prone grid context");
    assert.match(html, /\.coverage-record \{[^}]*display: flow-root;[^}]*break-inside: avoid;[^}]*page-break-inside: avoid;/su, "print coverage rows need a non-grid fragmentation context and both guards");
    assert.match(html, /\.coverage-record > div \{[^}]*float: left;[^}]*width: 50%/su, "print coverage facts need a readable two-column reflow");
    assert.match(html, /\.finding \{ break-inside: avoid-page; \}/u, "compact findings should not split across pages");
    assert.match(html, /section > h2 \{ break-after: avoid; \}/u, "section headings must stay with their first content");
    assert.match(html, /\.report-footer \{ display: none; \}/u, "the redundant screen footer must not create a print-only page");
    assert.match(html, /\.report-header\.state-clean ~ \.findings-empty \{ display: none; \}/u, "clean print must omit the redundant empty-findings block");
    assert.match(html, /overflow-wrap: anywhere/u);
    assert.match(html, /outline: var\(--ds-focus-width\) solid/u);
  });
});

function committedLedger(): ReviewLedger {
  return JSON.parse(readFileSync(new URL("../golden/report-surfaces/review-ledger.json", import.meta.url), "utf8")) as ReviewLedger;
}

/** A complete, current-shape manifest and a round bound to it: the positive control for the gate. */
function boundPassingFixture(): { ledger: ReviewLedger; manifest: Record<string, unknown>; fingerprint: string } {
  const fingerprint = "a".repeat(64);
  const reviewEnvironment = {
    reviewArtifactContractVersion: REVIEW_ARTIFACT_CONTRACT_VERSION,
    screenPixelContractVersion: 1,
    browser: "Chromium 141.0.7390.37",
    platform: "linux",
    architecture: "x64",
    nodeMajor: "24",
    deviceScaleFactor: 1,
    browserRenderArgs: [...REQUIRED_BROWSER_RENDER_ARGS],
    viewports: { desktop: { width: 1440, height: 1000 } },
    themes: ["light", "dark"],
    print: { media: "print", format: "A4 from CSS @page", rasterDpi: 110, rasterizer: "pdftoppm version 24.02.0", contentViewportCssPx: { width: 703, height: 1123 } },
  };
  const artifacts: Record<string, unknown>[] = [];
  const cells: Record<string, Record<string, unknown> & { status: "pass" }> = {};
  const hex = (index: number) => index.toString(16).padStart(64, "0");
  let index = 0;
  for (const state of ["clean", "findings", "infrastructure", "insufficient-coverage"]) {
    for (const theme of ["light", "dark"]) {
      for (const viewport of ["desktop", "tablet", "mobile"]) {
        const cell = `screen/${state}/${theme}/${viewport}`;
        const path = `${state}--${theme}--${viewport}.png`;
        const tiles = viewport === "desktop" ? [] : [{ path: `${state}--${theme}--${viewport}--tile-01.png` }];
        artifacts.push({ cell, kind: "screen", path, tiles, reviewArtifactFingerprint: hex(++index), pixels: { normalizedRgbaSha256: hex(++index) } });
        cells[cell] = { status: "pass", reviewer: "@Reviewer", reviewedAt: "2026-10-01T10:00:00.000Z", note: "Looked at the full page and every tile.", reviewArtifactFingerprint: hex(index - 1), reviewedRawSha256: hex(900), reviewedNormalizedRgbaSha256: hex(index), reviewedArtifacts: [path, ...tiles.map((tile) => tile.path)] };
      }
    }
    const pdfCell = `print/${state}/pdf`;
    artifacts.push({ cell: pdfCell, kind: "pdf", path: `${state}--a4.pdf`, pages: 2, reviewArtifactFingerprint: hex(++index) });
    cells[pdfCell] = { status: "pass", reviewer: "@Reviewer", reviewedAt: "2026-10-01T10:00:00.000Z", note: "Read both pages of the PDF.", reviewArtifactFingerprint: hex(index), reviewedRawSha256: hex(901), reviewedPages: [1, 2], reviewedArtifacts: [`${state}--a4.pdf`] };
    const rasterCell = `print/${state}/raster-set`;
    const pages = [{ path: `${state}--a4-page-1.png` }, { path: `${state}--a4-page-2.png` }];
    artifacts.push({ cell: rasterCell, kind: "raster-set", pages, reviewArtifactFingerprint: hex(++index) });
    cells[rasterCell] = { status: "pass", reviewer: "@Reviewer", reviewedAt: "2026-10-01T10:00:00.000Z", note: "Compared both rasters with the PDF.", reviewArtifactFingerprint: hex(index), reviewedRawSha256: [hex(902), hex(903)], reviewedPages: [1, 2], reviewedArtifacts: pages.map((page) => page.path) };
  }
  const physicalArtifacts = { screens: 24, pdfs: 4, rasterPages: 8 };
  const manifest = { reviewEnvironment, observedEnvironment: { platformRelease: "6.18.44", node: "v24.21.0" }, artifacts, physicalArtifacts };
  const ledger = committedLedger();
  const round: ReviewRound = {
    round: ledger.rounds.length + 1,
    record: "current",
    outcome: "pass",
    reviewedAt: "2026-10-01T10:00:00.000Z",
    reviewers: [{ handle: "@Reviewer", kind: "human" }],
    binding: { reviewInputFingerprint: fingerprint, renderManifestGeneratedAt: "2026-10-01T09:00:00.000Z", reviewEnvironment: structuredClone(reviewEnvironment) },
    physicalArtifactsReviewed: { ...physicalArtifacts },
    findings: { blocker: 0, high: 0, medium: 0, low: 0 },
    note: "Synthetic positive control for the strict local gate.",
    cells,
  };
  ledger.rounds.push(round);
  return { ledger, manifest, fingerprint };
}

describe("report-surface human review gate", () => {
  it("accepts every Chromium-family four-part browser version and rejects an unmeasurable one", () => {
    for (const accepted of [
      "Google Chrome 152.0.7977.64",
      "Google Chrome for Testing 141.0.7390.37",
      "Chromium 141.0.7390.37",
      "Chromium 141.0.7390.37 built on Debian 13",
      "Microsoft Edge 140.0.3485.54",
    ]) {
      assert.equal(isMeasurableBrowserVersion(accepted), true, `a supported Chromium-based browser was rejected: ${accepted}`);
    }
    for (const rejected of ["Chrome", "HeadlessChrome/141.0.7390.37", "Chromium 141.0.7390", "", "141.0.7390.37", "Chromium\n141.0.7390.37"]) {
      assert.equal(isMeasurableBrowserVersion(rejected), false, `an unmeasurable browser string was accepted: ${JSON.stringify(rejected)}`);
    }
    assert.equal(isMeasurableBrowserVersion(undefined), false);
    assert.ok(BROWSER_VERSION_PATTERN.unicode, "the pattern is a unicode regular expression");
  });

  it("records the 2026-09-18 FAIL as a structural round, and the strict local gate stays red on it", () => {
    const ledger = committedLedger();
    const { rounds, latest } = validateReviewLedger(ledger);
    assert.equal(rounds, 2);
    assert.equal(ledger.rounds[0]!.outcome, "pass", "the 0.2.3 review stays on record as the pass it was");
    assert.equal(ledger.rounds[0]!.record, "historical");
    assert.equal(latest.outcome, "fail");
    assert.equal(latest.record, "historical-reconstruction", "a round written after the fact must say so");
    assert.deepEqual(latest.findings, { blocker: 1, high: 3, medium: 4, low: 0 });
    assert.equal(latest.binding, null, "no fingerprint or environment was recorded in 2026-09-18 and none is invented");
    assert.ok(latest.reviewers.every((reviewer) => reviewer.kind === "not-recorded" && reviewer.handle === null),
      "the public record names no reviewer handle, so the ledger names none");
    const { manifest, fingerprint } = boundPassingFixture();
    assert.throws(() => assessHumanGate(committedLedger(), manifest, fingerprint), /latest human review round 2 is FAIL \(2026-09-18/u);
  });

  it("passes only a latest human round bound to the current inputs, environment and cells", () => {
    const { ledger, manifest, fingerprint } = boundPassingFixture();
    assert.equal(assessHumanGate(ledger, manifest, fingerprint).round, 3, "positive control: a genuinely bound round passes");

    // Mutation: a passing round over changed inputs is not a review of those inputs.
    assert.throws(() => assessHumanGate(ledger, manifest, "b".repeat(64)), /bound to a different source\/input revision/u);

    // Observations may drift without re-reviewing; the declared environment may not.
    const observedOnly = structuredClone(manifest);
    (observedOnly.observedEnvironment as Record<string, string>).platformRelease = "6.19.0";
    (observedOnly.observedEnvironment as Record<string, string>).node = "v24.99.1";
    assert.equal(assessHumanGate(ledger, observedOnly, fingerprint).round, 3, "a kernel or Node patch update must not unbind a review");
    const otherBrowser = structuredClone(manifest);
    (otherBrowser.reviewEnvironment as Record<string, string>).browser = "Google Chrome 152.0.7977.64";
    assert.throws(() => assessHumanGate(ledger, otherBrowser, fingerprint), /different declared browser\/platform\/render environment/u);

    // One changed cell fingerprint is a different rendered artifact.
    const changedCell = structuredClone(ledger);
    changedCell.rounds.at(-1)!.cells!["print/findings/pdf"]!.reviewArtifactFingerprint = "c".repeat(64);
    assert.throws(() => assessHumanGate(changedCell, manifest, fingerprint), /print\/findings\/pdf: strict local human review is bound to a different rendered artifact/u);

    // A screen cell is reviewed as its full page AND its tiles.
    const missingTile = structuredClone(ledger);
    missingTile.rounds.at(-1)!.cells!["screen/clean/light/mobile"]!.reviewedArtifacts = ["clean--light--mobile.png"];
    assert.throws(() => assessHumanGate(missingTile, manifest, fingerprint), /reviewed screen artifacts are not named exactly/u);

    // An agent review is recorded honestly and does not pass the human gate.
    const agentOnly = structuredClone(ledger);
    agentOnly.rounds.at(-1)!.reviewers = [{ handle: "@Reviewer", kind: "agent", model: "example-review-model" }];
    assert.throws(() => assessHumanGate(agentOnly, manifest, fingerprint), /has no human reviewer/u);

    // An earlier pass never carries forward over a later failed round.
    const laterFail = structuredClone(ledger);
    laterFail.rounds.push({ ...structuredClone(ledger.rounds[1]!), round: 4, record: "current", reviewedAt: "2026-10-02" });
    assert.throws(() => assessHumanGate(laterFail, manifest, fingerprint), /latest human review round 4 is FAIL/u);
  });

  it("rejects a ledger round whose record contradicts its outcome", () => {
    const failed = (mutate: (ledger: ReviewLedger) => void, expected: RegExp) => {
      const { ledger } = boundPassingFixture();
      mutate(ledger);
      assert.throws(() => validateReviewLedger(ledger), expected);
    };
    failed((ledger) => { ledger.rounds.at(-1)!.cells!["screen/clean/dark/tablet"]!.status = "fail"; }, /contains a cell that did not pass/u);
    failed((ledger) => { ledger.rounds.at(-1)!.findings.high = 1; }, /cannot carry a blocker or high finding/u);
    failed((ledger) => { ledger.rounds.at(-1)!.reviewers = [{ handle: null, kind: "agent" }]; }, /must name its model or tool/u);
    failed((ledger) => { ledger.rounds.at(-1)!.reviewers = [{ handle: "@Reviewer", kind: "human", model: "example-review-model" }]; }, /does not carry a model label/u);
    failed((ledger) => { ledger.rounds.at(-1)!.round = 7; }, /numbered in order/u);
    failed((ledger) => { ledger.rounds.at(-1)!.binding = null; }, /must bind inputs and environment/u);
    failed((ledger) => { delete ledger.rounds.at(-1)!.cells!["print/clean/raster-set"]; }, /must cover all 32 cells/u);
    failed((ledger) => { Object.assign(ledger.rounds[1]!, { findings: { blocker: 0, high: 0, medium: 0, low: 0 } }); }, /must record a finding or a failed cell/u);
    failed((ledger) => { delete ledger.rounds[1]!.source; }, /must name its source record/u);
    failed((ledger) => { (ledger.rounds.at(-1)!.binding!.reviewEnvironment as Record<string, unknown>).platformRelease = "6.18.44"; },
      new RegExp(`binds exactly ${DECLARED_ENVIRONMENT_FIELDS.join(", ")}`, "u"));
    failed((ledger) => { ledger.schemaVersion = 4; }, /human ledger schema drift/u);
  });
});
